__Assignment3__

**Q12. Feature Selection using Statistical Understanding**


Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain: Impact on overfitting and model performance

In [22]:
#1. Compute Correlation matrix

import pandas as pd
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(iris.data,columns=iris.feature_names)

corr_matrix = df.corr()

#print(corr_matrix)
#df.head()
corr_matrix

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
sepal length (cm),1.000000,-0.117570,0.871754,0.817941
sepal width (cm),-0.117570,1.000000,-0.428440,-0.366126
petal length (cm),0.871754,-0.428440,1.000000,0.962865
petal width (cm),0.817941,-0.366126,0.962865,1.000000

In [28]:
# Identify highly correlated feature pairs
import pandas as pd
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(iris.data,columns=iris.feature_names)

corr_matrix = df.corr()

#print(corr_matrix)
#df.head()
corr_matrix


high_corr_pairs = []

threshold = 0.8

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        corr_value = corr_matrix.iloc[i, j]
        if abs(corr_value) >= threshold:
            high_corr_pairs.append((corr_matrix.columns[i],corr_matrix.columns[j],corr_value))

high_corr_pairs

[('petal length (cm)', 'sepal length (cm)', np.float64(0.8717537758865838)),
 ('petal width (cm)', 'sepal length (cm)', np.float64(0.8179411262715758)),
 ('petal width (cm)', 'petal length (cm)', np.float64(0.962865431402796))]

In [31]:
#3. Drop redundant features

df_reduced = df.drop(columns=["petal width (cm)"])

df_reduced.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)
0                5.1               3.5                1.4
1                4.9               3.0                1.4
2                4.7               3.2                1.3
3                4.6               3.1                1.5
4                5.0               3.6                1.4

In [ ]:
#4. Explain: Impact on overfitting and model performance
Dropping redundant, highly correlated features reduces overfitting by lowering model complexity and variance, 
leading to better generalization and more stable performance on unseen data.